services:
  app:
    build: .
    image: laravelpostgresdockerized:configured
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgresdata:/var/lib/postgresql

volumes:
  postgresdata: